// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvexerjrbqzrkbzqswxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZXhlcmpyYnF6cmtienFzd3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzQ5OTcsImV4cCI6MjA2ODAxMDk5N30.JU2Fs8eluZddU1iSdCz5v3uhZglGkfuDawTu23iFsYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});